// =========================================================
//  AMBIENT CINEMATIC (60-80) -- percussions ultra rares + tom solitaire -- extrait de patterns_genre.scd
// =========================================================
(
~kickSteps  = (0!16); ~kickAmp = 0;
~hatSteps   = (0!16);
~snareSteps = (0!16);
~clapSteps  = (0!16);
~percInst = \tom; ~tomFreq = 60;
~percSteps  = [1,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]; ~percAmp = 0.3;
~reload.value; "=== AMBIENT CINEMATIC -- pas de kick ===".postln;
)
