// =========================================================
//  NEUROFUNK (174) -- breakbeat complex + 32th rolls -- extrait de patterns_genre.scd
// =========================================================
(
~kickSteps  = [1,0,0,0, 0,0,1,0, 0,0,1,0, 1,0,0,1]; ~kickAmp = 0.55;
~kickFreq=58;~kickPitchAmt=4.5;~kickDecay=0.15;~kickDrive=2.0;~kickClick=0.4;
~hatSteps   = [1,1,1,1, 0,1,1,1, 1,1,1,1, 0,1,1,1]; ~hatAmp = 0.14;
~snareSteps = [0,0,0,1, 1,0,0,0, 0,1,0,0, 1,0,1,1]; ~snareAmp = 0.55;
~snareFreq=260;~snareNoiseAmt=0.75;~snareDecay=0.08;
~clapSteps  = (0!16);
~percSteps  = (0!16);
~reload.value; "=== NEUROFUNK DNB 174 BPM ===".postln;
)
