// =========================================================
//  HARDCORE GABBER (180) -- kick gabber distorted intense, hihat absent -- extrait de patterns_genre.scd
// =========================================================
(
~kickSteps  = [1,0,1,0, 1,0,1,0, 1,0,1,0, 1,0,1,0]; ~kickAmp = 0.65;
~kickFreq=60;~kickPitchAmt=5.0;~kickDecay=0.18;~kickDrive=4.0;~kickClick=0.35;
~hatSteps   = (0!16); ~hatAmp = 0;
~snareSteps = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,0]; ~snareAmp = 0.5;
~clapSteps  = (0!16);
~percSteps  = (0!16);
~reload.value; "=== HARDCORE GABBER 180 BPM ===".postln;
)
